cam1/gscam_publisher:
  ros__parameters:
    gscam_config: 'udpsrc caps=application/x-rtp, sampling=YCbCr-4:2:2, depth=8, width=1920, height=1080 port=5004 ! rtpvrawdepay ! videoconvert ! fpsdisplaysink video-sink=xvimagesink text-overlay=true sync=false'
    preroll: False
    use_gst_timestamps: False
    frame_id: 'cam1_frame'
